import { type NextRequest, NextResponse } from "next/server"
import JSZip from "jszip"

export async function GET(request: NextRequest) {
  try {
    const zip = new JSZip()

    // Create a mock project scaffold
    zip.file(
      "README.md",
      `# AI Swarm Arena Generated Project

This project was generated by the AI Swarm Arena.

## Structure
- \`/frontend\` - Next.js React application
- \`/backend\` - FastAPI server
- \`/docs\` - Architecture documentation

## Getting Started
1. Install dependencies: \`npm install\` (frontend) and \`pip install -r requirements.txt\` (backend)
2. Run the development servers
3. Visit http://localhost:3000

Generated at: ${new Date().toISOString()}
`,
    )

    zip.file(
      "package.json",
      JSON.stringify(
        {
          name: "ai-swarm-generated-project",
          version: "0.1.0",
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^14.0.0",
            react: "^18.0.0",
            "react-dom": "^18.0.0",
          },
        },
        null,
        2,
      ),
    )

    zip.file(
      "architecture.json",
      JSON.stringify(
        {
          frontend: {
            framework: "Next.js",
            components: ["Dashboard", "Visualization", "Chat"],
            features: ["Real-time updates", "WebSocket connection"],
          },
          backend: {
            framework: "FastAPI",
            endpoints: ["/api/prompt", "/api/download", "/ws"],
            features: ["Agent simulation", "WebSocket support"],
          },
          database: {
            type: "Supabase PostgreSQL",
            tables: ["agents", "messages", "projects"],
          },
        },
        null,
        2,
      ),
    )

    // Generate ZIP file
    const zipBlob = await zip.generateAsync({ type: "nodebuffer" })

    return new NextResponse(zipBlob, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="ai-swarm-project.zip"',
      },
    })
  } catch (error) {
    console.error("Error generating download:", error)
    return NextResponse.json({ error: "Failed to generate download" }, { status: 500 })
  }
}
