import os, base64, requests
from dotenv import load_dotenv

load_dotenv()

ELEVEN_BASE = "https://api.elevenlabs.io/v1"

def speak_text(text: str, voice_id: str) -> str:
    """Return base64 audio (mp3) generated by ElevenLabs TTS."""
    api_key = os.getenv("ELEVENLABS_API_KEY")
    url = f"{ELEVEN_BASE}/text-to-speech/{voice_id}?optimize_streaming_latency=0"
    headers = {
        "xi-api-key": api_key,
        "accept": "audio/mpeg",
        "Content-Type": "application/json"
    }
    payload = {
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.4, "similarity_boost": 0.7}
    }
    r = requests.post(url, headers=headers, json=payload, timeout=60)
    r.raise_for_status()
    return base64.b64encode(r.content).decode("utf-8")
